# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "John Lyon's Photography"
subtitle: "Taken whenever"
author:  "John Lyon"
header:
 title: "Photos"
 subtitle: "by John"
footer:
 name: "Hey there, I am John"
 bio: "an occasional, very amateur photographer"
social_urls:
  twitter: "https://twitter.com/jozzas"
  instagram: "https://www.instagram.com/jozzas/"
  github: "https://github.com/jozzas"
